---
title: "Ejercicio_Estadistica_Intro"
author: "Francisco Alfaro B"
date: "2024-01-22"
output: github_document
---

#Cargando Base de Datos
```{r}

library(dplyr)
library(tidyverse)

data <- read.csv("C:\\Users\\kir8d\\OneDrive\\Desktop\\Data Science\\Experto en Ciencia de datos\\Iowa_Liquor_Sales.csv",
                           stringsAsFactors = FALSE,
                           header = TRUE)

```

#Transformando la Base de Datos
```{r}

datos <- data %>% 
  mutate(Sale..Dollars. = (as.numeric(substr(data$Sale..Dollars.,2,15))),
         City = toupper(City),
         Date = as.Date(Date,format = "%m/%d/%Y"),
         Año = lubridate::year(Date)) %>% 
  rename(Ventas = Sale..Dollars.,
         Ciudad = City,
         Categoria = Category.Name,
         Nombre_Tienda = Store.Name)

```

#¿Cuál el top 5 de tiendas (promedio de ventas), para el año 2016, para la ciudad CEDAR RAPIDS? 
```{r}

datos %>% 
  filter(Ciudad == "CEDAR RAPIDS" & Año == "2016") %>% 
  group_by(Nombre_Tienda) %>% 
  summarize(Promedio_Ventas = mean(Ventas, na.rm = T)) %>% 
  arrange(-Promedio_Ventas) %>% 
  head(Promedio_Ventas, n = 5L)

```

#¿Cuáles fueron los 5 últimos vendedores (promedio de ventas, para el 2016, para DAVENPORT)? 
```{r}

datos %>% 
  filter(Ciudad == "DAVENPORT" & Año == "2016") %>% 
  group_by(Vendor.Name) %>% 
  summarize(Promedio_Ventas = mean(Ventas, na.rm = T)) %>% 
  arrange(Promedio_Ventas) %>% 
  head(Promedio_Ventas, n = 5L)

```

#¿Cuál es el top 5 de productos más vendidos, para el 2016 y 2017, por ciudad?
```{r}

datos %>%
  filter(Año == "2016" | Año == "2017") %>%
  group_by(Ciudad,Año,Item.Description) %>% 
  summarise_at(vars(Ventas),
               list(Cant_Ventas = ~ sum(.,na.rm = TRUE))) %>%
  select(Ciudad, Cant_Ventas, Año, Item.Description) %>%
  pivot_wider(names_from  = c(Ciudad,Año),
              values_from = c(Cant_Ventas),
              names_prefix = "Ventas_",
              values_fill = 0) %>%
  arrange(-n()) %>%
  head(n = 5L)

```























